# Generated by Django 3.2.12 on 2023-05-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='director',
        ),
    ]
