# Generated by Django 3.2.12 on 2023-05-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.DeleteModel(
            name='ArticleLike',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
