# Generated by Django 3.2.13 on 2023-05-22 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20230519_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_comment',
        ),
        migrations.AddField(
            model_name='article',
            name='article_like',
            field=models.ManyToManyField(blank=True, related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
