<<<<<<< HEAD
# Generated by Django 3.2.13 on 2023-05-18 08:26
=======
# Generated by Django 3.2.13 on 2023-05-18 07:48
>>>>>>> c24faa64a78c0d8fdc508ada62ea66654712bfdf

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movies', '0001_initial'),
=======
        ('movies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
>>>>>>> c24faa64a78c0d8fdc508ada62ea66654712bfdf
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(related_name='users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
