# Generated by Django 3.2.13 on 2023-05-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
