# Generated by Django 3.2.13 on 2023-05-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
    ]
