# Generated by Django 3.2.13 on 2023-05-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
