# Generated by Django 3.2.13 on 2023-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_trailer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='profile_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
